### PR TITLE
feat: support setting quota for an individual bucket

### PR DESCRIPTION
**Pull request by dengchj**
There is no an api for set individual bucket quota, so I added it. 
Signed-off-by: Chenjiong Deng <dengchenjiong@gmail.com>

### CODE REVIEW

**Comment by rleimenstoll** [comment]
Hi Chenjiong,

Thanks for pointing out this use case in the API!  I definitely think this is something we would want to control via rgwadmin.

Looking at the Admin Ops API, it does look like the call to change a bucket is different enough to warrant a new method, although the actual quota contents are identical. Rather that duplicating that code in `set_individual_bucket_quota`, I think the we could abstract the quota string generation then create two new methods to handle user quotas and bucket quotas. I started this in #28, what do you think?

Best,
Ryan Leimenstoll

**Comment by dengchj** [comment]
> Hi Chenjiong,
> 
> Thanks for pointing out this use case in the API! I definitely think this is something we would want to control via rgwadmin.
> 
> Looking at the Admin Ops API, it does look like the call to change a bucket is different enough to warrant a new method, although the actual quota contents are identical. Rather that duplicating that code in `set_individual_bucket_quota`, I think the we could abstract the quota string generation then create two new methods to handle user quotas and bucket quotas. I started this in #28, what do you think?
> 
> Best,
> Ryan Leimenstoll

My previous idea was that the designed api could correspond to the [official api](http://docs.ceph.com/docs/master/radosgw/adminops/#quotas) one by one, and it was also convenient for api users to consult and understand. But when I saw your solution, this kind of demand does not seem to be necessary. Yours solution is good，I agree.

**Comment by rleimenstoll** [comment]
Hi Chengjiong, 

We merged #28 to include this functionality a release will be available shortly today. With that, I am going to close out this PR.

Thanks!
Ryan

**Comment by liammonahan** [comment]
Hi @dengchj 

We released this in https://github.com/UMIACS/rgwadmin/releases/tag/1.2.4

**Pull request closed without merging**
